version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: node-api-skeleton-app
    restart: always
    environment:
      NODE_ENV: development
    command: ["nodemon", "--trace-warnings",  "app.mjs", "| pino-pretty"]
    user: 1000:1000
    ports:
      - "3001:3001"
    volumes:
      - .:/home/app/

  cron:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: node-api-skeleton-cron
    restart: always
    environment:
      NODE_ENV: development
    command: [ "nodemon", "--trace-warnings",  "cron.mjs", "| pino-pretty" ]
    user: 1000:1000
    volumes:
      - .:/home/app/

  assistant:
    build:
      context: .
      dockerfile: Dockerfile.assistant
    container_name: node-api-skeleton-assistant
    volumes:
      - .:/home/app
