version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: node-api-skeleton-app
    restart: always
    environment:
      NODE_ENV: development
    command: ['pm2-runtime', 'start', 'ecosystem.config.cjs', '--watch', '--env', 'development']
    user: 1000:1000
    ports:
      - "3001:3001"
    volumes:
      - .:/home/app/

  assistant:
    build:
      context: .
      dockerfile: Dockerfile.assistant
    container_name: node-api-skeleton-assistant
    volumes:
      - .:/home/app
